export const brandData = [
    { name: "СНГ", brand: "VENDOR1" },
    { name: "ИНОМАРКИ", brand: "VENDOR2" },
    { name: "ЕВРОПЕЙСКИЕ", brand: "VENDOR3" },
    { name: "НЕМЕЦКИЕ", brand: "VENDOR4" },
    { name: "ФРАНЦУЗСКИЕ", brand: "VENDOR5" },
    { name: "ИТАЛЬЯНСКИЕ", brand: "VENDOR6", special: true },
    { name: "ЯПОНСКИЕ", brand: "VENDOR7" },
    { name: "АМЕРИКАНСКИЕ", brand: "VENDOR8" },
    { name: "КОРЕЙСКИЕ", brand: "VENDOR9" },
    { name: "КИТАЙСКИЕ", brand: "VENDOR10" },
    { name: "РОССИЙСКИЕ", brand: "VENDOR11", special: true },
    { name: "УКРАИНСКИЕ😆", brand: "VENDOR12", special: true },
    // { name: "ПУСТОЙ", brand: "VENDOR13", special: true },
    { name: "АНГЛИЙСКИЕ", brand: "VENDOR14", special: true },
    { name: "Abarth", brand: "ABARTH" },
    { name: "AC", brand: "AC" },
    { name: "Acura", brand: "ACURA" },
    { name: "Adler", brand: "ADLER" },
    { name: "Aito", brand: "AITO" },
    { name: "Aiways", brand: "AIWAYS" },
    { name: "Aixam", brand: "AIXAM" },
    { name: "Alfa Romeo", brand: "ALFA_ROMEO" },
    { name: "Alpina", brand: "ALPINA" },
    { name: "Alpine", brand: "ALPINE" },
    { name: "Aro", brand: "ARO" },
    { name: "Asia", brand: "ASIA" },
    { name: "Aston Martin", brand: "ASTON_MARTIN" },
    { name: "Audi", brand: "AUDI" },
    { name: "Aurus", brand: "AURUS" },
    { name: "Austin", brand: "AUSTIN" },
    { name: "Avatr", brand: "AVATR" },
    { name: "BAIC", brand: "BAIC" },
    { name: "Bajaj", brand: "BAJAJ" },
    { name: "Baltijas Dzips", brand: "BALTIJAS_DZIPS" },
    { name: "Baojun", brand: "BAOJUN" },
    { name: "BAW", brand: "BAW" },
    { name: "Belgee", brand: "BELGEE" },
    { name: "Bentley", brand: "BENTLEY" },
    { name: "BMW", brand: "BMW" },
    { name: "Borgward", brand: "BORGWARD" },
    { name: "Brilliance", brand: "BRILLIANCE" },
    { name: "Bugatti", brand: "BUGATTI" },
    { name: "Buick", brand: "BUICK" },
    { name: "BYD", brand: "BYD" },
    { name: "Cadillac", brand: "CADILLAC" },
    { name: "Chana", brand: "CHANA" },
    { name: "Changan", brand: "CHANGAN" },
    { name: "Changfeng", brand: "CHANGFENG" },
    { name: "CHERY", brand: "CHERY" },
    { name: "Chevrolet", brand: "CHEVROLET" },
    { name: "Chrysler", brand: "CHRYSLER" },
    { name: "Ciimo", brand: "CIIMO" },
    { name: "Citroen", brand: "CITROEN" },
    { name: "Coda", brand: "CODA" },
    { name: "Cupra", brand: "CUPRA" },
    { name: "Dacia", brand: "DACIA" },
    { name: "Dadi", brand: "DADI" },
    { name: "Daewoo", brand: "DAEWOO" },
    { name: "Daihatsu", brand: "DAIHATSU" },
    { name: "Daimler", brand: "DAIMLER" },
    { name: "Datsun", brand: "DATSUN" },
    { name: "Dayun", brand: "DAYUN" },
    { name: "Delage", brand: "DELAGE" },
    { name: "DeLorean", brand: "DELOREAN" },
    { name: "Denza", brand: "DENZA" },
    { name: "Derways", brand: "DERWAYS" },
    { name: "Dodge", brand: "DODGE" },
    { name: "Dongfeng", brand: "DONGFENG" },
    { name: "Doninvest", brand: "DONINVEST" },
    { name: "DS", brand: "DS" },
    { name: "DW Hower", brand: "DW_HOWER" },
    { name: "Eagle", brand: "EAGLE" },
    { name: "Enovate", brand: "ENOVATE" },
    { name: "Everus", brand: "EVERUS" },
    { name: "Evolute", brand: "EVOLUTE" },
    { name: "Excalibur", brand: "EXCALIBUR" },
    { name: "EXEED", brand: "EXEED" },
    { name: "Facel Vega", brand: "FACEL_VEGA" },
    { name: "FAW", brand: "FAW" },
    { name: "Ferrari", brand: "FERRARI" },
    { name: "Fiat", brand: "FIAT" },
    { name: "Fisker", brand: "FISKER" },
    { name: "Ford", brand: "FORD" },
    { name: "Forthing", brand: "FORTHING" },
    { name: "Foton", brand: "FOTON" },
    { name: "FSO", brand: "FSO" },
    { name: "GAC", brand: "GAC" },
    { name: "GAC Aion", brand: "AION" },
    { name: "GAC Trumpchi", brand: "TRUMPCHI" },
    { name: "Geely", brand: "GEELY" },
    { name: "Genesis", brand: "GENESIS" },
    { name: "Geo", brand: "GEO" },
    { name: "GMC", brand: "GMC" },
    { name: "Great Wall", brand: "GREAT_WALL" },
    { name: "Hafei", brand: "HAFEI" },
    { name: "Haima", brand: "HAIMA" },
    { name: "Haval", brand: "HAVAL" },
    { name: "Hawtai", brand: "HAWTAI" },
    { name: "Hennessey", brand: "HENNESSEY" },
    { name: "HiPhi", brand: "HIPHI" },
    { name: "Honda", brand: "HONDA" },
    { name: "Hongqi", brand: "HONGQI" },
    { name: "Hozon", brand: "HOZON" },
    { name: "HuangHai", brand: "HUANGHAI" },
    { name: "Hudson", brand: "HUDSON" },
    { name: "Hummer", brand: "HUMMER" },
    { name: "Hyundai", brand: "HYUNDAI" },
    { name: "iCar", brand: "ICAR" },
    { name: "IM Motors (Zhiji)", brand: "IM_MOTORS" },
    { name: "Ineos", brand: "INEOS" },
    { name: "Infiniti", brand: "INFINITI" },
    { name: "Innocenti", brand: "INNOCENTI" },
    { name: "International Harvester", brand: "INTERNATIONAL" },
    { name: "Iran Khodro", brand: "IRAN_KHODRO" },
    { name: "Isuzu", brand: "ISUZU" },
    { name: "JAC", brand: "JAC" },
    { name: "Jaecoo", brand: "JAECOO" },
    { name: "Jaguar", brand: "JAGUAR" },
    { name: "Jeep", brand: "JEEP" },
    { name: "Jetour", brand: "JETOUR" },
    { name: "Jetta", brand: "JETTA" },
    { name: "Jidu", brand: "JIDU" },
    { name: "Jinbei", brand: "JINBEI" },
    { name: "JMC", brand: "JMC" },
    { name: "Kaiyi", brand: "KAIYI" },
    { name: "Kawei", brand: "KAWEI" },
    { name: "KGM", brand: "KGM" },
    { name: "Kia", brand: "KIA" },
    { name: "Knewstar", brand: "KNEWSTAR" },
    { name: "Koenigsegg", brand: "KOENIGSEGG" },
    { name: "Lada (ВАЗ)", brand: "VAZ" },
    { name: "Lamborghini", brand: "LAMBORGHINI" },
    { name: "Lancia", brand: "LANCIA" },
    { name: "Land Rover", brand: "LAND_ROVER" },
    { name: "Landwind", brand: "LANDWIND" },
    { name: "Leapmotor", brand: "LEAPMOTOR" },
    { name: "LEVC", brand: "LEVC" },
    { name: "Lexus", brand: "LEXUS" },
    { name: "Liebao Motor", brand: "LIEBAO" },
    { name: "Lifan", brand: "LIFAN" },
    { name: "Lincoln", brand: "LINCOLN" },
    { name: "Livan", brand: "LIVAN" },
    { name: "LiXiang", brand: "LIXIANG" },
    { name: "Lotus", brand: "LOTUS" },
    { name: "Lucid", brand: "LUCID" },
    { name: "Luxeed", brand: "LUXEED" },
    { name: "Luxgen", brand: "LUXGEN" },
    { name: "Lynk & Co", brand: "LYNK_CO" },
    { name: "M-Hero", brand: "M_HERO" },
    { name: "Mahindra", brand: "MAHINDRA" },
    { name: "Maple", brand: "MAPLE" },
    { name: "Maserati", brand: "MASERATI" },
    { name: "Maxus", brand: "MAXUS" },
    { name: "Maybach", brand: "MAYBACH" },
    { name: "Mazda", brand: "MAZDA" },
    { name: "McLaren", brand: "MCLAREN" },
    { name: "Mercedes-Benz", brand: "MERCEDES" },
    { name: "Mercury", brand: "MERCURY" },
    { name: "Metrocab", brand: "METROCAB" },
    { name: "MG", brand: "MG" },
    { name: "Mini", brand: "MINI" },
    { name: "Mitsubishi", brand: "MITSUBISHI" },
    { name: "Mitsuoka", brand: "MITSUOKA" },
    { name: "Morgan", brand: "MORGAN" },
    { name: "Nevo", brand: "NEVO" },
    { name: "Nio", brand: "NIO" },
    { name: "Nissan", brand: "NISSAN" },
    { name: "Oldsmobile", brand: "OLDSMOBILE" },
    { name: "OMODA", brand: "OMODA" },
    { name: "Opel", brand: "OPEL" },
    { name: "Ora", brand: "ORA" },
    { name: "Oshan", brand: "OSHAN" },
    { name: "Oting", brand: "OTING" },
    { name: "Pagani", brand: "PAGANI" },
    { name: "Peugeot", brand: "PEUGEOT" },
    { name: "Plymouth", brand: "PLYMOUTH" },
    { name: "Polar Stone (Jishi)", brand: "POLAR_STONE_JISHI" },
    { name: "Polestar", brand: "POLESTAR" },
    { name: "Pontiac", brand: "PONTIAC" },
    { name: "Porsche", brand: "PORSCHE" },
    { name: "Proton", brand: "PROTON" },
    { name: "Puch", brand: "PUCH" },
    { name: "Qingling", brand: "QINGLING" },
    { name: "Qoros", brand: "QOROS" },
    { name: "Ram", brand: "RAM" },
    { name: "Ravon", brand: "RAVON" },
    { name: "Reliant", brand: "RELIANT" },
    { name: "Renault", brand: "RENAULT" },
    { name: "Renault Samsung", brand: "SAMSUNG" },
    { name: "Rising Auto", brand: "RISING_AUTO" },
    { name: "Rivian", brand: "RIVIAN" },
    { name: "Roewe", brand: "ROEWE" },
    { name: "Rolls-Royce", brand: "ROLLS_ROYCE" },
    { name: "Rover", brand: "ROVER" },
    { name: "Rox", brand: "ROX" },
    { name: "Saab", brand: "SAAB" },
    { name: "Sandstorm", brand: "SANDSTORM" },
    { name: "Saturn", brand: "SATURN" },
    { name: "Scion", brand: "SCION" },
    { name: "SEAT", brand: "SEAT" },
    { name: "Seres", brand: "SERES" },
    { name: "ShuangHuan", brand: "SHUANGHUAN" },
    { name: "Simca", brand: "SIMCA" },
    { name: "Skoda", brand: "SKODA" },
    { name: "Skywell", brand: "SKYWELL" },
    { name: "Smart", brand: "SMART" },
    { name: "Solaris", brand: "SOLARIS" },
    { name: "Sollers", brand: "SOLLERS" },
    { name: "Soueast", brand: "SOUEAST" },
    { name: "SsangYong", brand: "SSANGYONG" },
    { name: "Stelato", brand: "STELATO" },
    { name: "Steyr", brand: "STEYR" },
    { name: "Subaru", brand: "SUBARU" },
    { name: "Suzuki", brand: "SUZUKI" },
    { name: "SWM", brand: "SWM" },
    { name: "Tank", brand: "TANK" },
    { name: "Tata", brand: "TATA" },
    { name: "Tatra", brand: "TATRA" },
    { name: "Tesla", brand: "TESLA" },
    { name: "Tianma", brand: "TIANMA" },
    { name: "Tianye", brand: "TIANYE" },
    { name: "Tofas", brand: "TOFAS" },
    { name: "Toyota", brand: "TOYOTA" },
    { name: "Trabant", brand: "TRABANT" },
    { name: "Triumph", brand: "TRIUMPH" },
    { name: "Vauxhall", brand: "VAUXHALL" },
    { name: "Venucia", brand: "VENUCIA" },
    { name: "VGV", brand: "VGV" },
    { name: "Volkswagen", brand: "VOLKSWAGEN" },
    { name: "Volvo", brand: "VOLVO" },
    { name: "Vortex", brand: "VORTEX" },
    { name: "Voyah", brand: "VOYAH" },
    { name: "Wanderer", brand: "WANDERER" },
    { name: "Wartburg", brand: "WARTBURG" },
    { name: "Weltmeister", brand: "WELTMEISTER" },
    { name: "Wey", brand: "WEY" },
    { name: "Willys", brand: "WILLYS" },
    { name: "Wuling", brand: "WULING" },
    { name: "Xcite", brand: "XCITE" },
    { name: "Xiaomi", brand: "XIAOMI" },
    { name: "Xin Kai", brand: "XIN_KAI" },
    { name: "Xpeng", brand: "XPENG" },
    { name: "Yema", brand: "YEMA" },
    { name: "Yulon", brand: "YULON" },
    { name: "Zeekr", brand: "ZEEKR" },
    { name: "Zotye", brand: "ZOTYE" },
    { name: "ZX", brand: "ZX" },
    { name: "ГАЗ", brand: "GAZ" },
    { name: "ЗАЗ", brand: "ZAZ" },
    { name: "ЗИЛ", brand: "ZIL" },
    { name: "ЗиС", brand: "ZIS" },
    { name: "Иж", brand: "IG" },
    { name: "Канонир", brand: "KANONIR" },
    { name: "Комбат", brand: "KOMBAT" },
    { name: "ЛуАЗ", brand: "LUAZ" },
    { name: "Москвич", brand: "MOSCVICH" },
    { name: "Самоделки", brand: "PROMO_AUTO" },
    { name: "СМЗ", brand: "SMZ" },
    { name: "ТагАЗ", brand: "TAGAZ" },
    { name: "УАЗ", brand: "UAZ" }
];